### ISSUE TITLE
Dependencies with other parts of oxart

### ISSUE THREAD

**Issue by ljstephenson** [OxfordIonTrapGroup/oxart-devices#3]
Some of the frontend scripts (e.g. [thorlabs_mdt69xb_controller.py](oxart/frontend/thorlabs_mdt69xb_controller.py)) import `oxart.tools.common_args`, which isn't available to those outside of Oxford, so those scripts don't work.

As far as I remember, that function was a helper method during the transition to sipyco, and just wrapped the `verbosity_args` function from sipyco. It doesn't appear to be necessary as per [aqctl_agilent_6671a.py](oxart/frontend/aqctl_agilent_6671a.py).

I'm happy to prepare a PR changing all of the frontend scripts to the latter format if someone can confirm that `oxart.tools.common_args` is functionally equivalent to `sipyco.common_args.verbosity_args`.

**Comment by dnadlinger** [comment]
```py
# verbosity_args() was renamed to add_common_args() in ARTIQ 5.0 and then back
# to verbosity_args() in SiPyCo; support both.
try:
    from sipyco.common_args import verbosity_args as add_common_args
except ImportError:
    try:
        from artiq.tools import add_common_args
    except ImportError:
        from artiq.tools import verbosity_args as add_common_args

__all__ = ['add_common_args']
```

**Comment by dnadlinger** [comment]
We should just change all to the new API.

**Comment by ljstephenson** [comment]
I'll get on with that then!
